import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import Script from 'next/script'
import Navbar from './Navbar'
import PrayerTimes from './PrayerTimes'
import Donate from './Donate'
import Programs from './Programs'
import Services from './Services'
import Mission from './Mission'
import Imams from './Imams'
import Carousel from './Carousel'
import AntCarousel from './AntCarousel'
import Maps from './Maps'
import Footer from './Footer'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false) 




  return (
    <div className={darkMode? "dark" : ""}>
      <Head>
        <title>Al Faruq Islamic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='wrapper'>
        <div className='navWrapper w-full'>
          <Navbar />
        </div>
        {/* <Carousel /> */}
        <AntCarousel />
        <PrayerTimes />
        <Donate />
        <Programs />
        <Services />
        <Mission />
        <Imams />
        <Maps />
        <Footer />


            
        </div>

      </main>

      <Script>
        {`
        
        setTimeout(function() {
          location.reload();
        }, 3600000);
        
        `}
      </Script>      
    </div>    
  )
}
