import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import Script from 'next/script'
import Navbar from './Navbar'
import PrayerTimes from './PrayerTimes'
import Carousel from './Carousel'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false) 




  return (
    <div className={darkMode? "dark" : ""}>
      <Head>
        <title>Al Faruq Islamic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='wrapper'>
        <div className='navWrapper w-full'>
          <Navbar />
        </div>
        <Carousel />
        <PrayerTimes />
        
        <section className='min-h-screen bg-gray-900 text-white'>
          <h1>Hello World 2</h1>
          <h6>Add dkdj fkfek jfk kl jegje gjej lj elg jel jeljlegj ljlgjlej lejglejgl jlgejgjg lgjergljeg ljgllj le jllgj e jg</h6>
          <p>Qqsddd kfhkwfh k hwfk hfkhf kfhjkefh kwhfkj fk ek kwhd kwhfkf hkfhwkhf khfkwh kwfhk whk ekh khewk fhek ffh kw hkwf hkhfkw hfkwnfwkl fnlgf n el elegnel wkbhkw bken keng lken gkegk bfknelk nelnj lghenglew nnek gbekfgb wekgnelkg el glegnlew nbwklgfbkenbl ghlrglengf klnbgekgfkegfb jke bgkgke hnlrngle lrgel k nbklrhlr hnlen ghelnhlrnh lfff.</p>
        </section>  
          
        <section className='min-h-screen bg-gray-500 text-white'>
          <h1>footer</h1>
          <a target="_blank" href="https://icons8.com/icon/JFFOqqqKFmhA/mosque">Mosque</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </section>     
        </div>

      </main>

      <Script>
        {`
        
        setTimeout(function() {
          location.reload();
        }, 3600000);
        
        `}
      </Script>      
    </div>    
  )
}
