import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import { Alert } from "flowbite-react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)


  return (
    <div className={darkMode? "dark" : ""}>
      <Head>
        <title>Al Faruq Islamic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 dark:bg-gray-900 dark:text-white'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Al Faruq Islamic Centre</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className='cursor-pointer text-xl'></BsFillMoonStarsFill></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Prayer Times</a></li>
            </ul>
          </nav>
        </section>        
      </main>
    </div>
  )
}
