import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react'
import Script from 'next/script'
import Navbar from './Navbar'
import PrayerTimes from './PrayerTimes'
import Carousel from './Carousel'
import AntCarousel from './AntCarousel'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false) 




  return (
    <div className={darkMode? "dark" : ""}>
      <Head>
        <title>Al Faruq Islamic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='wrapper'>
        <div className='navWrapper w-full'>
          <Navbar />
        </div>
        {/* <Carousel /> */}
        <AntCarousel />
        <PrayerTimes />
        
        <section className='min-h-screen bg-gray-900 text-white'>
          <div className='container p-10 pt-50'>
          <h1>Hello World 2</h1>
          <h6>Add dkdj fkfek jfk kl jegje gjej lj elg jel jeljlegj ljlgjlej lejglejgl jlgejgjg lgjergljeg ljgllj le jllgj e jg</h6>
          <p>Qqsddd kfhkwfh k hwfk hfkhf kfhjkefh kwhfkj fk ek kwhd kwhfkf hkfhwkhf khfkwh kwfhk whk ekh khewk fhek ffh kw hkwf hkhfkw hfkwnfwkl fnlgf n el elegnel wkbhkw bken keng lken gkegk bfknelk nelnj lghenglew nnek gbekfgb wekgnelkg el glegnlew nbwklgfbkenbl ghlrglengf klnbgekgfkegfb jke bgkgke hnlrngle lrgel k nbklrhlr hnlen ghelnhlrnh lfff.</p>
          <div>
            <svg className='w-10 h-10' viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" fill="#000000">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_iconCarrier"> <title>mosque</title> 
            <g id="mosque"> 
            <circle cx="43.5" cy="8.5" r="1.5"></circle> 
            <circle cx="47" cy="16" r="1"></circle> 
            <line x1="54" y1="8.463" x2="54" y2="9.878" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="54" y1="14.122" x2="54" y2="15.537" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="50.463" y1="12" x2="51.878" y2="12" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="56.122" y1="12" x2="57.537" y2="12" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <path d="M55.689,39.588A13.8,13.8,0,0,0,57,33.636c0-6.326-9-11.454-9-11.454a24.758,24.758,0,0,0-2.146,1.425" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <path d="M20.846,19a12.891,12.891,0,0,0,1.287-5.714C22.133,7.605,14.5,3,14.5,3S6.867,7.605,6.867,13.286A12.891,12.891,0,0,0,8.154,19Z" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <path d="M44,31.533a9.9,9.9,0,0,0,2-5.9c0-6.326-14-11.454-14-11.454S18,19.31,18,25.636a9.888,9.888,0,0,0,2,5.9" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <path d="M44.389,40H56.5A1.5,1.5,0,0,1,58,41.5h0A1.5,1.5,0,0,1,56.5,43H44.324" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <rect x="17" y="32" width="30" height="3" rx="1.5" ry="1.5" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></rect> 
            <polyline points="29 60.554 29 43 32 40 35 43 35 60.554" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></polyline> 
            <line x1="32" y1="14" x2="32" y2="10" fill="none" stroke="#ffffff" strokeLinejoin="round" strokeWidth="2px"></line> 
            <path d="M32.191,4.66a3,3,0,0,0,3.166,5.1" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <path d="M19.564,44H8.5A1.5,1.5,0,0,0,7,45.5H7A1.5,1.5,0,0,0,8.5,47H19.637" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></path> 
            <line x1="51" y1="43" x2="51" y2="48" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="48" y1="43" x2="48" y2="48" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="39" y1="35" x2="39" y2="50" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="25" y1="35" x2="25" y2="50" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="13" y1="47.364" x2="13" y2="52" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="16" y1="47.364" x2="16" y2="52" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="13" y1="39" x2="13" y2="43.564" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="16" y1="39" x2="16" y2="43.564" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="60" y1="61" x2="4" y2="61" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="9" y1="44" x2="9" y2="19" fill="none" stroke="#ffffff" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="20" y1="21" x2="20" y2="20" fill="none" stroke="#ffffff" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="55" y1="43" x2="55" y2="61" fill="none" stroke="#ffffff" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="9" y1="47" x2="9" y2="61" fill="none" stroke="#ffffff" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="20" y1="61" x2="20" y2="35" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            <line x1="44" y1="61" x2="44" y2="35" fill="none" stroke="#ffffff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2px"></line> 
            </g> </g>
            </svg>
          </div>
          </div>
        </section>  
          
        <section className='min-h-screen bg-gray-500 text-white'>
          <h1>footer</h1>
          <a target="_blank" href="https://icons8.com/icon/JFFOqqqKFmhA/mosque">Mosque</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </section>     
        </div>

      </main>

      <Script>
        {`
        
        setTimeout(function() {
          location.reload();
        }, 3600000);
        
        `}
      </Script>      
    </div>    
  )
}
